version: '3.4'

services:
  sugar:
    # directly using an image instead of building our own
    image: node:16-alpine
    working_dir: /usr/src/app
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DB_CONNECTION_STRING: postgres://postgres:postgres@postgres:5438/tea
    ports:
      - 3030:3030
      - 9229:9229
    # runs yarn at runtime so mounts are active
    command: sh -c "ls -al && yarn --no-progress && yarn start:dev"
    # mounting our API source directory
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
  postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      volumes: 
        - postgres-data:/var/lib/postgresql/data
volumes:
  ? postgres-data