version: '3.4'

services:
  sugar:
    image: sugar
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3030:3030
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/app.js"]
  postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
